// <auto-generated/>
namespace ComInterfaceGenerator.Tests
{
    internal unsafe partial class NativeExportsNE
    {
        internal unsafe partial class ImplicitThis
        {
            internal unsafe partial interface INativeObject
            {
                [global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
                internal partial interface Native : INativeObject
                {
                }
            }
        }
    }
}
namespace ComInterfaceGenerator.Tests
{
    internal unsafe partial class NativeExportsNE
    {
        internal unsafe partial class NoImplicitThis
        {
            internal unsafe partial interface IStaticMethodTable
            {
                [global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
                internal partial interface Native : IStaticMethodTable
                {
                }
            }
        }
    }
}
namespace ComInterfaceGenerator.Tests
{
    internal unsafe partial class NativeExportsNE
    {
        internal unsafe partial class UnmanagedToManagedCustomMarshalling
        {
            internal unsafe partial interface INativeObject
            {
                [global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
                internal partial interface Native : INativeObject
                {
                }
            }
        }
    }
}
namespace ComInterfaceGenerator.Tests
{
    internal unsafe partial class NativeExportsNE
    {
        internal unsafe partial class UnmanagedToManagedCustomMarshalling
        {
            internal unsafe partial interface INativeObjectStateful
            {
                [global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
                internal partial interface Native : INativeObjectStateful
                {
                }
            }
        }
    }
}
