// <auto-generated />
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 152, 115, 133, 164, 251, 6, 110, 74, 129, 219, 53, 70, 27, 233, 153, 197 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.ComInterfaceGenerator", "42.42.42.42")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    global::ComInterfaceGenerator.Tests.ComInterfaces.IInt global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface.Get()
    {
        var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface));
        global::ComInterfaceGenerator.Tests.ComInterfaces.IInt __retVal;
        void* __retVal_native;
        int __invokeRetVal;
        {
            __invokeRetVal = ((delegate* unmanaged[MemberFunction]<void*, void**, int> )__vtable_native[3])(__this, &__retVal_native);
        }

        System.GC.KeepAlive(this);
        // Unmarshal - Convert native data to managed data.
        System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(__invokeRetVal);
        __retVal = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::ComInterfaceGenerator.Tests.ComInterfaces.IInt>.ConvertToManaged(__retVal_native);
        return __retVal;
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.ComInterfaceGenerator", "42.42.42.42")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    void global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface.Set(global::ComInterfaceGenerator.Tests.ComInterfaces.IInt value)
    {
        var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface));
        void* __value_native;
        int __invokeRetVal;
        // Marshal - Convert managed data to native data.
        __value_native = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::ComInterfaceGenerator.Tests.ComInterfaces.IInt>.ConvertToUnmanaged(value);
        {
            __invokeRetVal = ((delegate* unmanaged[MemberFunction]<void*, void*, int> )__vtable_native[4])(__this, __value_native);
        }

        System.GC.KeepAlive(this);
        // Unmarshal - Convert native data to managed data.
        System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(__invokeRetVal);
    }
}

file unsafe partial interface InterfaceImplementation
{
    [System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Get(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void** __invokeRetValUnmanaged__param)
    {
        global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface @this = default;
        ref void* __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
        global::ComInterfaceGenerator.Tests.ComInterfaces.IInt __invokeRetVal = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            __retVal = 0; // S_OK
            @this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface>(__this_native);
            __invokeRetVal = @this.Get();
            // Marshal - Convert managed data to native data.
            __invokeRetValUnmanaged = (void*)global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::ComInterfaceGenerator.Tests.ComInterfaces.IInt>.ConvertToUnmanaged(__invokeRetVal);
        }
        catch (System.Exception __exception)
        {
            __retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Set(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, void* __value_native)
    {
        global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface @this = default;
        global::ComInterfaceGenerator.Tests.ComInterfaces.IInt value = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            __retVal = 0; // S_OK
            value = global::System.Runtime.InteropServices.Marshalling.ComInterfaceMarshaller<global::ComInterfaceGenerator.Tests.ComInterfaces.IInt>.ConvertToManaged(__value_native);
            @this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface>(__this_native);
            @this.Set(value);
        }
        catch (System.Exception __exception)
        {
            __retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::ComInterfaceGenerator.Tests.ComInterfaces.IInterface), sizeof(void*) * 5);
        {
            nint v0, v1, v2;
            System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void**, int> )&ABI_Get;
            vtable[4] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, void*, int> )&ABI_Set;
        }

        return vtable;
    }
}

namespace ComInterfaceGenerator.Tests
{
    public static unsafe partial class ComInterfaces
    {
        [System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
        internal partial interface IInterface
        {
        }
    }
}

namespace ComInterfaceGenerator.Tests
{
    public static unsafe partial class ComInterfaces
    {
        internal partial interface IInterface
        {
        }
    }
}