// <auto-generated />
#pragma warning disable CS0612, CS0618
file unsafe class InterfaceInformation : System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static System.Guid Iid { get; } = new(new System.ReadOnlySpan<byte>(new byte[] { 124, 183, 82, 10, 139, 224, 116, 66, 161, 244, 26, 43, 242, 192, 126, 96 }));

    private static void** _vtable;
    public static void** ManagedVirtualMethodTable => _vtable != null ? _vtable : (_vtable = InterfaceImplementation.CreateManagedVirtualFunctionTable());
}

[System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::SharedTypes.ComInterfaces.ICustomCollectionStateful
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.ComInterfaceGenerator", "42.42.42.42")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> global::SharedTypes.ComInterfaces.ICustomCollectionStateful.Method(global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> p, int pSize, in global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pIn, in int pInSize, int pRefSize, ref global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pRef, out global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pOut, out int pOutSize)
    {
        var(__this, __vtable_native) = ((System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::SharedTypes.ComInterfaces.ICustomCollectionStateful));
        System.Runtime.CompilerServices.Unsafe.SkipInit(out pOut);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out pOutSize);
        byte* __p_native = default;
        byte* __pIn_native = default;
        byte* __pRef_native = default;
        byte* __pOut_native = default;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> __retVal = default;
        byte* __retVal_native = default;
        int __invokeRetVal = default;
        // Setup - Perform required setup.
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __retVal_native__marshaller = new();
        int __retVal_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __retVal_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pOut_native__marshaller = new();
        int __pOut_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pOut_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pRef_native__marshaller = new();
        int __pRef_native__numElements;
        int __pRef_native__lastIndexMarshalled = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pRef_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pIn_native__marshaller = new();
        int __pIn_native__numElements;
        int __pIn_native__lastIndexMarshalled = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pIn_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __p_native__marshaller = new();
        int __p_native__numElements;
        int __p_native__lastIndexMarshalled = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __p_native__numElements);
        try
        {
            // Marshal - Convert managed data to native data.
            __pRef_native__marshaller.FromManaged(pRef);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __pRef_native__managedSpan = __pRef_native__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pRef_native__nativeSpan = __pRef_native__marshaller.GetUnmanagedValuesDestination();
                for (int __i0 = 0; __i0 < __pRef_native__managedSpan.Length; ++__i0, ++__pRef_native__lastIndexMarshalled)
                {
                    __pRef_native__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__pRef_native__managedSpan[__i0]);
                }
            }

            __pIn_native__marshaller.FromManaged(pIn);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __pIn_native__managedSpan = __pIn_native__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pIn_native__nativeSpan = __pIn_native__marshaller.GetUnmanagedValuesDestination();
                for (int __i0 = 0; __i0 < __pIn_native__managedSpan.Length; ++__i0, ++__pIn_native__lastIndexMarshalled)
                {
                    __pIn_native__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__pIn_native__managedSpan[__i0]);
                }
            }

            __p_native__marshaller.FromManaged(p);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __p_native__managedSpan = __p_native__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __p_native__nativeSpan = __p_native__marshaller.GetUnmanagedValuesDestination();
                for (int __i0 = 0; __i0 < __p_native__managedSpan.Length; ++__i0, ++__p_native__lastIndexMarshalled)
                {
                    __p_native__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__p_native__managedSpan[__i0]);
                }
            }

            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (int* __pOutSize_native = &pOutSize)
            fixed (int* __pInSize_native = &pInSize)
            {
                // PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
                __pRef_native = __pRef_native__marshaller.ToUnmanaged();
                __pIn_native = __pIn_native__marshaller.ToUnmanaged();
                __p_native = __p_native__marshaller.ToUnmanaged();
                __invokeRetVal = ((delegate* unmanaged[MemberFunction]<void*, byte*, int, byte**, int*, int, byte**, byte**, int*, byte**, int> )__vtable_native[3])(__this, __p_native, pSize, &__pIn_native, __pInSize_native, pRefSize, &__pRef_native, &__pOut_native, __pOutSize_native, &__retVal_native);
            }

            System.GC.KeepAlive(this);
            // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
            __retVal_native__marshaller.FromUnmanaged(__retVal_native);
            __pOut_native__marshaller.FromUnmanaged(__pOut_native);
            __pRef_native__marshaller.FromUnmanaged(__pRef_native);
            // Unmarshal - Convert native data to managed data.
            System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(__invokeRetVal);
            __retVal_native__numElements = 10;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __retVal_native__nativeSpan = __retVal_native__marshaller.GetUnmanagedValuesSource(__retVal_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __retVal_native__managedSpan = __retVal_native__marshaller.GetManagedValuesDestination(__retVal_native__numElements);
                for (int __i0 = 0; __i0 < __retVal_native__numElements; ++__i0)
                {
                    __retVal_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__retVal_native__nativeSpan[__i0]);
                }
            }

            __retVal = __retVal_native__marshaller.ToManaged();
            __pOut_native__numElements = pOutSize;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pOut_native__nativeSpan = __pOut_native__marshaller.GetUnmanagedValuesSource(__pOut_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __pOut_native__managedSpan = __pOut_native__marshaller.GetManagedValuesDestination(__pOut_native__numElements);
                for (int __i0 = 0; __i0 < __pOut_native__numElements; ++__i0)
                {
                    __pOut_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__pOut_native__nativeSpan[__i0]);
                }
            }

            pOut = __pOut_native__marshaller.ToManaged();
            __pRef_native__numElements = pRefSize;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pRef_native__nativeSpan = __pRef_native__marshaller.GetUnmanagedValuesSource(__pRef_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __pRef_native__managedSpan = __pRef_native__marshaller.GetManagedValuesDestination(__pRef_native__numElements);
                for (int __i0 = 0; __i0 < __pRef_native__numElements; ++__i0)
                {
                    __pRef_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__pRef_native__nativeSpan[__i0]);
                }
            }

            pRef = __pRef_native__marshaller.ToManaged();
        }
        finally
        {
            // Cleanup - Perform required cleanup.
            __retVal_native__marshaller.Free();
            __pOut_native__marshaller.Free();
            _ = __pRef_native__lastIndexMarshalled;
            __pRef_native__marshaller.Free();
            _ = __pIn_native__lastIndexMarshalled;
            __pIn_native__marshaller.Free();
            _ = __p_native__lastIndexMarshalled;
            __p_native__marshaller.Free();
        }

        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    [System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Method(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, byte* __p_native, int pSize, byte** __pIn_native__param, int* __pInSize_native__param, int pRefSize, byte** __pRef_native__param, byte** __pOut_native__param, int* __pOutSize_native__param, byte** __invokeRetValUnmanaged__param)
    {
        global::SharedTypes.ComInterfaces.ICustomCollectionStateful @this = default;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> p = default;
        byte* __pIn_native = *__pIn_native__param;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pIn = default;
        int __pInSize_native = *__pInSize_native__param;
        int pInSize = default;
        byte* __pRef_native__out = default;
        byte* __pRef_native = *__pRef_native__param;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pRef = default;
        byte* __pOut_native__out = default;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> pOut = default;
        int __pOutSize_native__out = default;
        int pOutSize = default;
        byte* __invokeRetValUnmanaged__out = default;
        global::SharedTypes.ComInterfaces.TestCollection<global::SharedTypes.ComInterfaces.Element> __invokeRetVal = default;
        int __retVal = default;
        // Setup - Perform required setup.
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __invokeRetValUnmanaged__marshaller = new();
        int __invokeRetValUnmanaged__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __invokeRetValUnmanaged__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pOut_native__marshaller = new();
        int __pOut_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pOut_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pRef_native__marshaller = new();
        int __pRef_native__numElements;
        int __pRef_native__lastIndexMarshalled = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pRef_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __pIn_native__marshaller = new();
        int __pIn_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __pIn_native__numElements);
        scoped global::SharedTypes.ComInterfaces.Marshaller<global::SharedTypes.ComInterfaces.Element, global::SharedTypes.ComInterfaces.ElementMarshaller.Native>.Ref __p_native__marshaller = new();
        int __p_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __p_native__numElements);
        try
        {
            // UnmarshalCapture - Capture the native data into marshaller instances in case conversion to managed data throws an exception.
            __pRef_native__marshaller.FromUnmanaged(__pRef_native);
            __pIn_native__marshaller.FromUnmanaged(__pIn_native);
            __p_native__marshaller.FromUnmanaged(__p_native);
            // Unmarshal - Convert native data to managed data.
            __retVal = 0; // S_OK
            __pRef_native__numElements = pRefSize;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pRef_native__nativeSpan = __pRef_native__marshaller.GetUnmanagedValuesSource(__pRef_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __pRef_native__managedSpan = __pRef_native__marshaller.GetManagedValuesDestination(__pRef_native__numElements);
                for (int __i0 = 0; __i0 < __pRef_native__numElements; ++__i0)
                {
                    __pRef_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__pRef_native__nativeSpan[__i0]);
                }
            }

            pRef = __pRef_native__marshaller.ToManaged();
            pInSize = __pInSize_native;
            __pIn_native__numElements = pInSize;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pIn_native__nativeSpan = __pIn_native__marshaller.GetUnmanagedValuesSource(__pIn_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __pIn_native__managedSpan = __pIn_native__marshaller.GetManagedValuesDestination(__pIn_native__numElements);
                for (int __i0 = 0; __i0 < __pIn_native__numElements; ++__i0)
                {
                    __pIn_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__pIn_native__nativeSpan[__i0]);
                }
            }

            pIn = __pIn_native__marshaller.ToManaged();
            __p_native__numElements = pSize;
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __p_native__nativeSpan = __p_native__marshaller.GetUnmanagedValuesSource(__p_native__numElements);
                System.Span<global::SharedTypes.ComInterfaces.Element> __p_native__managedSpan = __p_native__marshaller.GetManagedValuesDestination(__p_native__numElements);
                for (int __i0 = 0; __i0 < __p_native__numElements; ++__i0)
                {
                    __p_native__managedSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToManaged(__p_native__nativeSpan[__i0]);
                }
            }

            p = __p_native__marshaller.ToManaged();
            @this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::SharedTypes.ComInterfaces.ICustomCollectionStateful>(__this_native);
            __invokeRetVal = @this.Method(p, pSize, in pIn, in pInSize, pRefSize, ref pRef, out pOut, out pOutSize);
            // PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
            __invokeRetValUnmanaged__out = __invokeRetValUnmanaged__marshaller.ToUnmanaged();
            __pOut_native__out = __pOut_native__marshaller.ToUnmanaged();
            __pRef_native__out = __pRef_native__marshaller.ToUnmanaged();
            // Marshal - Convert managed data to native data.
            __invokeRetValUnmanaged__marshaller.FromManaged(__invokeRetVal);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __invokeRetValUnmanaged__managedSpan = __invokeRetValUnmanaged__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __invokeRetValUnmanaged__nativeSpan = __invokeRetValUnmanaged__marshaller.GetUnmanagedValuesDestination();
                __invokeRetValUnmanaged__nativeSpan.Clear();
                __invokeRetValUnmanaged__out = (byte*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref __invokeRetValUnmanaged__nativeSpan.GetPinnableReference());
                for (int __i0 = 0; __i0 < __invokeRetValUnmanaged__managedSpan.Length; ++__i0)
                {
                    __invokeRetValUnmanaged__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__invokeRetValUnmanaged__managedSpan[__i0]);
                }
            }

            __pOutSize_native__out = pOutSize;
            __pOut_native__marshaller.FromManaged(pOut);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __pOut_native__managedSpan = __pOut_native__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pOut_native__nativeSpan = __pOut_native__marshaller.GetUnmanagedValuesDestination();
                __pOut_native__nativeSpan.Clear();
                __pOut_native__out = (byte*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref __pOut_native__nativeSpan.GetPinnableReference());
                for (int __i0 = 0; __i0 < __pOut_native__managedSpan.Length; ++__i0)
                {
                    __pOut_native__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__pOut_native__managedSpan[__i0]);
                }
            }

            __pRef_native__marshaller.FromManaged(pRef);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.Element> __pRef_native__managedSpan = __pRef_native__marshaller.GetManagedValuesSource();
                System.Span<global::SharedTypes.ComInterfaces.ElementMarshaller.Native> __pRef_native__nativeSpan = __pRef_native__marshaller.GetUnmanagedValuesDestination();
                __pRef_native__out = (byte*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref __pRef_native__nativeSpan.GetPinnableReference());
                for (int __i0 = 0; __i0 < __pRef_native__managedSpan.Length; ++__i0, ++__pRef_native__lastIndexMarshalled)
                {
                    __pRef_native__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.ElementMarshaller.ConvertToUnmanaged(__pRef_native__managedSpan[__i0]);
                }
            }
        }
        catch (System.Exception __exception)
        {
            __retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
            // Cleanup - Perform required cleanup.
            _ = __pRef_native__lastIndexMarshalled;
            __pRef_native__marshaller.Free();
            return __retVal;
        }

        // AssignOut - Assign to parameters
        *__invokeRetValUnmanaged__param = __invokeRetValUnmanaged__out;
        *__pOutSize_native__param = __pOutSize_native__out;
        *__pOut_native__param = __pOut_native__out;
        *__pRef_native__param = __pRef_native__out;
        // Cleanup - Perform required cleanup.
        _ = __pRef_native__lastIndexMarshalled;
        __pRef_native__marshaller.Free();
        __pIn_native__marshaller.Free();
        __p_native__marshaller.Free();
        return __retVal;
    }
}

file unsafe partial interface InterfaceImplementation
{
    internal static void** CreateManagedVirtualFunctionTable()
    {
        void** vtable = (void**)System.Runtime.CompilerServices.RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(global::SharedTypes.ComInterfaces.ICustomCollectionStateful), sizeof(void*) * 4);
        {
            nint v0, v1, v2;
            System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out v0, out v1, out v2);
            vtable[0] = (void*)v0;
            vtable[1] = (void*)v1;
            vtable[2] = (void*)v2;
        }

        {
            vtable[3] = (void*)(delegate* unmanaged[MemberFunction]<System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, byte*, int, byte**, int*, int, byte**, byte**, int*, byte**, int> )&ABI_Method;
        }

        return vtable;
    }
}

namespace SharedTypes.ComInterfaces
{
    [System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    partial interface ICustomCollectionStateful
    {
    }
}

namespace SharedTypes.ComInterfaces
{
    partial interface ICustomCollectionStateful
    {
    }
}